name: publish-branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to publish."
        required: false
        default: "master"
      tag:
        description: "The tag to publish to."
        required: false
        default: "latest"
jobs:
  publish:
    uses: adobe/aio-reusable-workflows/.github/workflows/version-bump-publish.yml@main